In [1]:
import tensorflow as tf


# 定义tensorflow里面的常量
a = tf.constant([1, 2], dtype=tf.float32, shape=[1, 2], name="a")
b = tf.constant([3, 4], dtype=tf.float32, shape=[1, 2], name="b")
c = tf.constant([5, 6], dtype=tf.float32, shape=[1, 2], name="c")

In [2]:
# 启动tensorflow session
sess = tf.Session()

In [3]:
# 计算变量a
sess.run(a)

array([[1., 2.]], dtype=float32)

In [4]:
# 定义s = a + b
s = tf.add(a, b, name="sum")
sess.run(s)

array([[4., 6.]], dtype=float32)

In [5]:
# 定义m = c * s
m = tf.multiply(c, s, name="multiply")
sess.run(m)

array([[20., 36.]], dtype=float32)

In [6]:
# 定义tensorflow里面的变量Variable
x = tf.Variable(0, name="counter")
one = tf.constant(1)
update = tf.assign(x, tf.add(x, one))

In [7]:
## 变量初始化运算
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(x))

0


In [9]:
## 执行一次+1运算
sess.run(update)
print(sess.run(x))

2


In [10]:
import numpy as np


# 定义tensorflow里面的变量placeholder
mat1 = tf.placeholder(tf.float32, shape=[1, 3], name="mat2")
mat2 = tf.placeholder(tf.float32, shape=[3, 1], name="mat1")
output = tf.matmul(mat1, mat2)

In [11]:
## 传入数据
sess.run([output],
         feed_dict={mat1: np.array([1, 2, 3]).reshape(1, 3),
                    mat2: np.array([4, 5, 6]).reshape(3, 1)})

[array([[32.]], dtype=float32)]

In [12]:
# 将计算过程的log记录下来，并使用tensorboard进行可视化
writer = tf.summary.FileWriter("logs/tensorflow_basic/", graph=sess.graph)